.PHONY: all

all: test/pyddd-ipa.so test/test-ipa

PYTHONROOT := /home/jondy/workspace/pytransform/python/usr/local
PYTHONINC := $(PYTHONROOT)/include/python2.7
PYTHONLIB := -L$(PYTHONROOT)/lib -lpython2.7
CFLAGS := -g -I$(PYTHONINC) -fPIC
CC := gcc

test/pyddd-ipa.so: ipa.c
	$(CC) -shared $(CFLAGS) $< -Wl,-lpthread -o $@

test/test-ipa: test/test-ipa.c ipa.c
	$(CC) -o $@ $(CFLAGS) -DTEST_IPA $< ipa.c $(PYTHONLIB) -Wl,-lpthread

test: test/test-ipa
	test/test-ipa
